### PR TITLE
Handstone can be enchanted with Efficiency and Fortune.

### PR DESCRIPTION
**Pull request by brotazoa**
Handstone can be enchanted with Efficiency; decreasing the amount of activations required to complete a recipe.

Handstone can be enchanted with Fortune; increasting recipe output using the same formulas for a similarly enchanted pickaxe.

### CODE REVIEW

**Comment by brotazoa** [comment]
My previous Pull Requests were for features/mechanics that I thought should really be part of this mod, but this one is a little different. While I was testing the mod, I found that you could already put an Unbreaking or Mending book on the Handstone, and the enchantments would work as expected. I figured I would see about making the other 'Tool' type enchantments work as well, and this is what I came up with. I Thought I would present this for your review, and see if you thought it is in scope for the mod.

**Comment by Wtoll** [comment]
I like the idea and agree that it makes sense within the scope of the mod. I think the efficiency implementation makes sense; however, I wonder if the fortune implementation makes sense having it hard coded. I would look into the way that pickaxes apply the fortune effect, I believe that it is defined through the loot tables system. I wonder if it would make more sense to change the way quern recipes are loaded to allow the fortune enchantment to defined in the recipe file similar to the pickaxe through the loot tables system.

**Comment by brotazoa** [comment]
I updated this branch with my 1.16 changes, and also rewrote the fortune code to work through the loot table system as per your suggestion.

Grinding recipes now support a "loot_table" property, allowing you to create loot tables, or use existing loot tables as a recipe result. I included one recipe that showcases the "loot_table" property: nether_quartz_ore.json

With the current implementation, if a recipe defines a loot table property, then the results of the loot table will be used instead of any "result" object property. Ideally, every recipe would be modified to use the loot table property, and custom loot tables would be written for any recipes that couldn't use an existing loot table. This would allow for the removal of the "result" object property from grinding recipes all together.

Let me know what you think.

**Comment by Vaerian** [comment]
Superseded by 90fedea

**Pull request closed without merging**
