### PR TITLE
Quern Blockstates

### PR DESCRIPTION
**Pull request by brotazoa**
Quern has Blockstates to show visually which Handstone is being used.
Handstone plays the item break sound when it breaks

### CODE REVIEW

**Comment by Wtoll** [comment]
The only potential issue I see is that using an integer system will prevent other mod authors from creating higher levels of hand-stones. I would probably shift the block state to a string system based upon the identifier the respective hand-stones are registered under.

**Comment by Wtoll** [comment]
Completely separate issue is that I haven't had the time to properly maintain this mod, but clearly there is a demand for that. The major hurdle right now is updating the 1.16 branch to the newest versions, so if you're interested in that, it would be a major help.

**Comment by Wtoll** [comment]
If you're interested in helping me maintain this mod I might start an organization to transfer ownership to a more community level so that mods that are more influential on the community can be collaboratively updated more easily.

**Comment by brotazoa** [comment]
I merged my 1.16 updates, and reworked the block states code as per your suggestion. The block state property is now achieved using a custom enum property. Let me know what you think.

**Comment by brotazoa** [comment]
On a side note, I am very interested in helping maintain this mod. It is simple enough that it shouldn't consume all of my time, and I understand you have other mods that take up a lot of your modding time.

**Comment by Vaerian** [comment]
Hi its me. Sorry I totally went MIA for a while, I ended up migrating github accounts (this is my new account) and kind of forgot that the mod existed, and also forgot my old password. I went ahead and made a team for the mod and invited you to it in case you're still interested in contributing. I'm gonna re-review your PRs and pull in the ones I think look good.

We also have a discord server for mods in the organization in case you're interested in joining. I'll add you to the simple quern developers role so you'll have access to the private development discussion channel. https://discord.gg/gHMN9mj

**Pull request closed without merging**
